[versions]
android-library = "7.4.2"
kotlin = "1.9.0"
ktlint = "11.5.1"
maven-publish = "0.25.2"
spotless = "6.17.0"

[plugins]

android-library = { id ="com.android.library", version.ref = "android-library" }
kotlin-multiplatform = { id ="org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id ="org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id ="org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spotless = { id ="com.diffplug.spotless", version.ref = "spotless" }
maven-publish = { id ="com.vanniktech.maven.publish", version.ref = "maven-publish" }
